---
- name: "scripts | stowing scripts"
  command: stow -t {{ ansible_user_dir }} scripts
  args:
    chdir: "{{ role_path }}/files"

- name: "scripts | chmodding scripts"
  command: chmod 755 -R {{ ansible_user_dir }}/.local/bin
