---
- name: "scripts | stowing scripts"
  command: stow -t {{ ansible_user_dir }} scripts
  args:
    chdir: "{{ role_path }}/files"

- name: "scripts | chmodding scripts"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    owner: jogiwa
    group: jogiwa
    mode: '0755'
    recurse: yes
