- name: "suckless | Install Depends"
  pacman:
    name: libx11
    state: present
  become: true

- name: "Suckless | clone repository" 
  git:
    repo: https://github.com/j0giwa/suckless-desktop
    dest: "{{ ansible_user_dir }}/.config/suckless"
    update: yes
    version: master

- name: "suckless | Install dwm"
  command: make clean install
  args:
    chdir: "{{ ansible_user_dir }}/.config/suckless/dwm"
  become: true

- name: "suckless | Install st"
  command: make clean install
  args:
    chdir: "{{ ansible_user_dir }}/.config/suckless/st"
  become: true

- name: "suckless | Install dmenu"
  command: make clean install
  args:
    chdir: "{{ ansible_user_dir }}/.config/suckless/dmenu"
  become: true
