- name: "suckless | Install Depends"
  pacman:
    name: libx11-dev
    state: present
  become: true

- name: "Suckless | clone repository" 
  git:
    repo: https://github.com/j0giwa/suckless-desktop
    dest: {{ ansible_user_dir }}/.config

- name: "suckless | Install dwm"
  command: make clean install
  args:
    chdir: "{{ ansible_user_dir }}/.config/suckless-desktop/dwm"
  become: true

- name: "suckless | Install st"
  command: make clean install
  args:
    chdir: "{{ ansible_user_dir }}/.config/suckless-desktop/st"
  become: true

- name: "suckless | Install dmenu"
  command: make clean install
  args:
    chdir: "{{ ansible_user_dir }}/.config/suckless-desktop/dmenu"
  become: true