---
- hosts: localhost
  connection: local
  become: true
  tasks:
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/dwm.yml
    - include: tasks/dmenu.yml
    - include: tasks/st.yml

