#!/usr/bin/env zsh

export ZDOTDIR="$HOME"/.config/zsh

# ==== Default Programms ====
export FETCH="nitch"
export TERMINAL="st"
export BROWSER="firefox"
export TERM="xterm-256color" # getting proper colors
export EDITOR="nvim"         # $EDITOR use nvim in terminal
#export EDITOR="emacsclient -t -a ''"    # $EDITOR use Emacs in terminal
#export VISUAL="emacsclient -c -a emacs" # $VISUAL use Emacs in GUI mode
#export PAGER="sh -c 'col -bx | bat -l man -p'"

export TEXPLATES="$HOME/Templates/latex"

# ==== XDG ====
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}

# Cleanup
export HISTFILE="${XDG_STATE_HOME}/zsh/history"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"
export GKT_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
export GKT2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export LESSHISTFILE="-" #Disable file
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export JAVA_HOME='/usr/lib/jvm/jdk-22-oracle-x64'
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export JDTLS_JVM_ARGS="-javaagent:$HOME/.local/lib/java/lombok.jar"

#export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
export KDEHOME="$XDG_CONFIG_HOME/kde"
export DALAMUD_HOME="/mnt/c/Users/jonas/AppData/Roaming/XIVLauncher/addon/Hooks/dev"

path+=$HOME/.config/emacs/bin
path+=$HOME/.local/bin
path+=$JAVA_HOME/bin
export PATH

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:-1,fg+:#d0d0d0,bg:-1,bg+:#262626
  --color=hl:#bd93f9,hl+:#5fd7ff,info:#ffb86c,marker:#ff79c6
  --color=prompt:#50fa7b,spinner:#ffb86c,pointer:#ff79c6,header:#6272a4
  --color=border:#262626,label:#aeaeae,query:#d9d9d9
  --border="rounded" --border-label="" --preview-window="border-rounded" --prompt="> "
  --marker=">" --pointer="◆" --separator="─" --scrollbar="│"'

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
