- name: Clone DMENU repository
  git:
    repo: https://github.com/j0giwa/dmenu.git
    dest: /home/jogiwa/./config/suckless/dmenu
  tags:
    - dmenu
    - suckless

- name: Copy DMENU headers
  copy:
    src: files/config/suckless/dmenu/config.h
    dest: /home/jogiwa/.config/suckless/dmenu/config.h
    owner: jogiwa
    group: jogiwa
  tags:
    - dmenu
    - suckless

- name: Build and install DMENU
  shell: |
    cd /home/jogiwa/.config/suckless/dmenu
    make install
  tags:
    - dmenu
    - suckless


