- name: packages
  package:
    name:
      - emacs
      - htop
      - zellij
      - neovim
      - tmux
      - tldr
      
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      
      - picom