- name: Clone ST repository
  git:
    repo: https://github.com/j0giwa/st.git
    dest: /home/jogiwa/suckless/st
  tags:
    - st
    - suckless

- name: Copy ST headers
  copy:
    src: files/config/suckless/st/config.h
    dest: /home/jogiwa/.config/suckless/st/config.h
    owner: jogiwa
    group: jogiwa
  tags:
    - st
    - suckless

- name: Build and install ST
  shell: |
    cd /home/jogiwa/.config/suckless/st
    make install
  tags:
    - st
    - suckless
