#!/bin/sh

# Activate Dbus
. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Set dpi
xrandr --dpi 92

# Remap some keys
remaps

setbg & # restore previous wallpaper

xrandr --output "eDP-1" --scale 1.3x1.3 && setbg # Scales my display to 120%

# Load Xresources
xrdb ${XDG_CONFIG_HOME:-$HOME.config}/X11/Xresources & xrdbpid=$!

# Autostart some Programs
#pidof -s dunst || dunst &
#pidof -s sxhkd || sxhkd &
pidof -s picom || picom &
pidof -s unclutter || unclutter &
pidof -s udiskie || udiskie  &
pidof -s emacs || /usr/bin/emacs --daemon &

#Wait fo xrdb if neccesary
[ -n "$xrdbpid" ] && wait "$xrdbpid"

