---
- name: "System | updating packages"
  pacman:
    update_cache: true
    upgrade: true
  become: true

- name: "System | updating AUR packages"
  pacman:
    update_cache: true
    upgrade: true
    executable: paru
  become: true
