---
- name: "zsh | installing zsh"
  pacman:
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present
  become: true

- name: "zsh | stow configs"
  command: stow -t {{ ansible_user_dir }} zsh
  args:
    chdir: "{{ role_path }}/files"
