---
- name: "kitty | Install kitty"
  pacman:
    name: kitty
    state: present
  become: true
  tags:
    - packages

- name: "kitty | stow configs"
  command: stow -t {{ ansible_user_dir }} kitty
  args:
    chdir: "{{ role_path }}/files"
  tags:
    - dotfiles
