---
- name: "Programming | installing c/c++"
  pacman:
    name: gcc
    state: present
  become: true

- name: "Programming | installing r"
  pacman:
    name: r
    state: present
  become: true

- name: "Programming | installing rustup"
  pacman:
    name: rustup
    state: present
  become: true

- name: "Programming | setting up rust"
  command: rustup default stable

- name: "Programming | installing java"
  pacman:
    name:
      - jdk-openjdk
      - maven
    state: present
  become: true
