---
- name: "Programming | installing c/c++"
  package:
    name: gcc
    state: present
  become: true

- name: "Programming | installing r"
  package:
    name: r
    state: present
  become: true

- name: "Programming | installing java"
  package:
    name:
      - jdk-openjdk
      - maven
    state: present
  become: true

- name: "Programming | installing plantuml"
  package:
    name: plantuml
    state: present
  become: true

- name: "Programming | installing man"
  package:
    name: man
    state: present
  become: true

- name: "Programming | installing tldr"
  package:
    name: tldr
    state: present
  become: true
