---
- name: "Programming | installing c/c++"
  pacman:
    name: gcc
    state: present
  become: true

- name: "Programming | installing r"
  pacman:
    name: r
    state: present
  become: true

- name: "Programming | installing rustup"
  pacman:
    name: rustup
    state: present
  become: true

- name: "Programming | setting up rust"
  command: rustup default stable

- name: "Programming | installing java"
  pacman:
    name:
      - jdk-openjdk
      - maven
    state: present
  become: true

- name: "Programming | installing plantuml"
  pacman:
    name: plantuml
    state: present
  become: true

- name: "Programming | installing node"
  pacman:
    name: npm
    state: present
  become: true

- name: "Programming | installing fzf"
  pacman:
    name: fzf
    state: present
  become: true

- name: "Programming | installing man"
  pacman:
    name: man
    state: present
  become: true

- name: "Programming | installing tldr"
  pacman:
    name: tldr
    state: present
  become: true
