---
- name: "DUNST | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: dunst_distribution_config

- name: "DUNST | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: dunst_distribution_config.stat.exists

- name: "DUNST | stow configs"
  command: stow -t {{ ansible_user_dir }} dunst
  args:
    chdir: "{{ role_path }}/files"
  tags:
    - dotfiles
