---
- name: "HerbstluftWM | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: herbstluft_distribution_config

- name: "HerbstluftWM | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: herbstluft_distribution_config.stat.exists

- name: "HerbstluftWM | stow configs"
  command: stow -t {{ ansible_user_dir }} herbstluftwm
  args:
    chdir: "{{ role_path }}/files"
  tags:
    - dotfiles
