---
- name: "herbstluftwm | Install herbstluftwm"
  package:
    name: herbstluftwm
    state: present
  become: true
  tags:
    - packages

- name: "herbstluftwm | stow configs"
  command: stow -t {{ ansible_user_dir }} herbstluftwm
  args:
    chdir: "{{ role_path }}/files"
  tags:
    - dotfiles
