---
- name: "DOOM | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: doom_distribution_config

- name: "DOOM | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: doom_distribution_config.stat.exists

- name: "DOOM | install Doom Emacs" 
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: "{{ ansible_user_dir }}/.config/emacs"
  tags:
    - packages

- name: "DOOM | stow configs (remember to 'doom sync')"
  command: stow -t {{ ansible_user_dir }} doom
  args:
    chdir: "{{ role_path }}/files"
  tags:
    - dotfiles
