- name: "DOOM | Install Depends"
  package:
    name:
      - fd
      - ripgrep
      - emacs
    state: present
  become: true
  tags:
    - packages

- name: "DOOM | install Doom Emacs" 
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: "{{ ansible_user_dir }}/.config/emacs"
  tags:
    - packages

- name: "DOOM | stow configs (remember to 'doom sync')"
  command: stow -t {{ ansible_user_dir }} doom
  args:
    chdir: "{{ role_path }}/files"
  tags:
    - dotfiles
