---
- name: "alacritty | installing alacritty"
  pacman:
    name: alacritty
    state: present
  become: true

- name: "alacritty | stow configs"
  command: stow -t {{ ansible_user_dir }} alacritty
  args:
    chdir: "{{ role_path }}/files"