---
- name: "awesome | Install awesome"
  pacman:
    name: awesome
    state: present
  become: true
  tags:
    - packages

- name: "awesome | stow configs"
  command: stow -t {{ ansible_user_dir }} awesome
  args:
    chdir: "{{ role_path }}/files"
  tags:
    - dotfiles
