---
- name: "Awesome | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: awesome_distribution_config

- name: "Awesome | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: awesome_distribution_config.stat.exists

- name: "awesome | stow configs"
  command: stow -t {{ ansible_user_dir }} awesome
  args:
    chdir: "{{ role_path }}/files"
  tags:
    - dotfiles
