---
- name: "xmonad | Install xmonad"
  pacman:
    name: 
      - xmonad
      - xmonad-contrib
      - xmobar
    state: present
  become: true

- name: "xmonad | stow configs"
  command: stow -t {{ ansible_user_dir }} xmonad xmobar
  args:
    chdir: "{{ role_path }}/files"
