---
- name: "Neovim | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: neovim_distribution_config

- name: "Neovim | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: neovim_distribution_config.stat.exists

#- name: "nvim | Install nvim"
#  pacman:
#    name: neovim
#    state: present
#  become: true

- name: "nvim | stow configs"
  command: stow -t {{ ansible_user_dir }} nvim
  args:
    chdir: "{{ role_path }}/files"
