---
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true

- name: "Neovim | {{ ansible_distribution }} | Install Repository"
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  become: true

- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  apt:
    name:
      - neovim
    state: present
  become: true
