---
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true
  tags:
    - packages

- name: "Neovim | {{ ansible_distribution }} | Clone"
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ ansible_user_dir }}/Projekte/neovim"
  tags:
    - packages

- name: "Neovim | {{ ansible_distribution }} | Install"
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  command: "make install"
  args:
    chdir: "{{ ansible_user_dir }}/Projekte/neovim"
  tags:
    - packages
