---
- name: "Neovim | {{ ansible_distribution }} | Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - unzip
      - ninja-build
      - gettext
      - curl
    state: present
  become: true
  tags:
    - packages

- name: "Neovim | {{ ansible_distribution }} | Clone"
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ ansible_user_dir }}/Projekte/neovim"
    update: yes
    version: master
  tags:
    - packages

- name: "Neovim | {{ ansible_distribution }} | Install"
  command: "make install"
  args:
    chdir: "{{ ansible_user_dir }}/Projekte/neovim"
  become: true
  tags:
    - packages
